apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: muc6qetuc-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/muc6qetuc-dotnet-basic-gitops